### ISSUE TITLE
TypeScript linting config doesn't fully work with current tsconfig.json

### ISSUE THREAD

**Issue by Vanilagy** [clickbar/eslint-config#17]
We have `prefer-nullish-coalescing` and `strict-boolean-expressions` enabled but these rules require that `strictNullChecks` be enabled in the tsconfig.json. I personally don't like `strictNullChecks`, as it basically forces you to pepper your code with a bunch of `if` and `!`. Don't like it. So I think it's good that it's off, but then those two linting rules don't make sense. I suggest removing them.

Additionally, I suggest that we enable `strict` in the tsconfig.json, but then turn off `strictNullChecks`. That's gonna give us nice things like no implicit "any" and more. In general, more strictness in the type checker is always welcome.

**Comment by saibotk** [comment]
We recommend using the tsconfig that Vue also uses: https://github.com/vuejs/tsconfig

Thus, it might be your tsconfig which is not yet up to date with our new default.

Anyway I'm going to close this issue for now, since this is nothing we can change in this repository :)

I suggest that null check opinions can be discussed further internally.

**Comment by Vanilagy** [comment]
Yah deffo
